### ISSUE TITLE
Kamanja compiled under scala 2.10 fails to serialize/deserialize messages in kafka

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1316]
When a user start Kamanja that has been built in scala 2.10 and attempts to process messages, the following exception appears even when Kamanja has all the necessary metadata added.

```
ERROR [pool-19-thread-1] - Failed to Deserialize/Execute. MessageName: at UK:{"Version":1,"Type":"Kafka","Name":"helloworldinput","TopicName":"helloworldinput","PartitionId":0}, UV:{"Version":1,"Offset":50}
com.ligadata.Exceptions.KamanjaException: Failed to Deserialize com.ligadata.kamanja.samples.messages.msg1
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:602) ~[KamanjaInternalDeps_2.10-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.InputAdapters.KamanjaKafkaConsumer.deserialize(KamanjaKafkaConsumer.scala:48) ~[KamanjaInternalDeps_2.10-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:319) [KamanjaInternalDeps_2.10-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.10-1.5.0.jar:1.5.0]
	at com.ligadata.InputAdapters.KamanjaKafkaConsumer$$anonfun$StartProcessing$4$$anon$1.run(KamanjaKafkaConsumer.scala:369) [KamanjaInternalDeps_2.10-1.5.0.jar:0.1-SNAPSHOT]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.10-1.5.0.jar:1.0]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.10-1.5.0.jar:1.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at com.ligadata.kamanja.samples.messages.V1000000.msg1.<init>(msg1.scala:119) ~[?:?]
	at com.ligadata.kamanja.samples.messages.V1000000.msg1.<init>(msg1.scala:342) ~[?:?]
	at com.ligadata.kamanja.samples.messages.V1000000.msg1$.createInstance(msg1.scala:26) ~[?:?]
	at com.ligadata.kamanja.samples.messages.V1000000.msg1$.createInstance(msg1.scala:16) ~[?:?]
	at com.ligadata.KamanjaManager.KamanjaMetadata$.getInstance(KamanjaMetadata.scala:1344) ~[kamanjamanager_2.10-1.5.0.jar:1.5.0]
	at com.ligadata.kamanja.serializer.CsvSerDeser.deserialize(CsvSerDeser.scala:366) ~[KamanjaInternalDeps_2.10-1.5.0.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaBase.AdaptersSerializeDeserializers$class.deserialize(BaseMessageContainer.scala:596) ~[KamanjaInternalDeps_2.10-1.5.0.jar:0.1-SNAPSHOT]
	... 7 more
```

**Comment by ligadata-saleh** [comment]
@ligadata-william  I can't replicate the exception you are getting also @ligadata-yousef  test 2.10 without any problems , can you please clean and recompile the source again , also can you please check the kafka version you are using the new consumer is working fine with "kafka_2.10-0.9.0.0" and "kafka_2.11-0.9.0.0" . 

Thanks
Saleh

**Comment by ligadata-dan** [comment]
@ligadata-saleh @ligadata-william 

Hi Saleh, not sure this is a kafka related issue.  Seems like msg1 implementation is missing a method or something.    Could be some scala 2.10 vs 2.11 msg compilation issue.

**Comment by ligadata-saleh** [comment]
Hi Dan ,

I couldn't replicate the problem , so i just assume the could be a kafka
2.10 consumer tried to connect to kafka 2.11 server , anyways it seems a
build issue more than anything else .

Thanks
Saleh
On Mon, Jul 11, 2016 at 8:51 PM Dank <notifications@github.com> wrote:

> @ligadata-saleh <https://github.com/ligadata-saleh> @ligadata-william
> <https://github.com/ligadata-william>
>
> Hi Saleh, not sure this is a kafka related issue. Seems like msg1
> implementation is missing a method or something. Could be some scala 2.10
> vs 2.11 msg compilation issue.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/LigaData/Kamanja/issues/1316#issuecomment-231811525>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKco6o3vsc1F4K_6sFuZln3_zZyOlDbUks5qUoKfgaJpZM4JJNpc>
> .
>
-- 

Thanks,

Saleh H. Abdallah

Senior Software Engineer

E: saleh@ligadata.com
[image: LD]

**Comment by ligadata-william** [comment]
If it were a kafka version issue, Kamanja never would have been able to read messages from kafka in the first place, so I imagine that isn’t the issue. I’m rebuilding Kamanja 2.10 and 2.11 from scratch. It really shouldn’t have an effect if I have the correct version of scala installed when I compile the metadata but we’ll see.

**Comment by ligadata-william** [comment]
I am completely unable to get Kamanja 1.5.0 working when compiled against scala 2.10. I've verified scala version, java version, kafka version, operating system version; everything. It quite simply isn't working. Even InitKVStores_*.sh scripts all fail to serialize/deserialize.

**Comment by ligadata-william** [comment]
Finally figured out the issue. I made sure that scala -version returned 2.10.5. However, we don't ever actually invoke scala when we run things. In fact, we're invoking scalac. When I ran scalac -version, it returned 2.11.7, which explains why I've been having issues (This is what sleep depravation does to me). I'm verifying quickly with the hello world app. Once it runs ok, I'll close this.

**Comment by ligadata-william** [comment]
Verified as working. Closing.
