### ISSUE TITLE
PMML models throw exception when "Range" is called

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1267]
When running PMML models that call the "Range" function, the below exception is thrown. There appears to be a version issue with guava that needs to be dealt with in Kamanja.

```
ERROR [pool-21-thread-1] - Failed to execute model:system.autompg
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Range.closed(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lcom/google/common/collect/Range;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2254) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3985) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4873) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.CacheUtil.getValue(CacheUtil.java:49) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.FieldValueUtil.getValidRanges(FieldValueUtil.java:544) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.FieldValueUtil.getStatus(FieldValueUtil.java:237) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.FieldValueUtil.prepare(FieldValueUtil.java:67) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.ModelEvaluator.prepare(ModelEvaluator.java:239) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.EvaluatorUtil.prepare(EvaluatorUtil.java:125) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at com.ligadata.jpmml.JpmmlAdapter$$anonfun$prepareFields$1$$anonfun$apply$2.apply(JpmmlFactoryOfModelInstanceFactory.scala:246) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.jpmml.JpmmlAdapter$$anonfun$prepareFields$1$$anonfun$apply$2.apply(JpmmlFactoryOfModelInstanceFactory.scala:245) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at scala.Option.fold(Option.scala:158) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.ligadata.jpmml.JpmmlAdapter$$anonfun$prepareFields$1.apply(JpmmlFactoryOfModelInstanceFactory.scala:245) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.jpmml.JpmmlAdapter$$anonfun$prepareFields$1.apply(JpmmlFactoryOfModelInstanceFactory.scala:243) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.ligadata.jpmml.JpmmlAdapter.prepareFields(JpmmlFactoryOfModelInstanceFactory.scala:243) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.jpmml.JpmmlAdapter.evaluateModel(JpmmlFactoryOfModelInstanceFactory.scala:197) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.jpmml.JpmmlAdapter.execute(JpmmlFactoryOfModelInstanceFactory.scala:186) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaBase.ModelInstance.execute(ModelBase.scala:601) ~[KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.LearningEngine.execute(LearningEngine.scala:194) [kamanjamanager_2.11-1.4.2.jar:1.4.2]
	at com.ligadata.KamanjaManager.ExecContextImpl.executeMessage(ExecContext.scala:117) [kamanjamanager_2.11-1.4.2.jar:1.4.2]
	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:266) [KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.11-1.4.2.jar:1.4.2]
	at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:311) [KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.11-1.4.2.jar:1.4.2]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(KafkaSimpleConsumer.scala:408) [KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at scala.util.control.Breaks.breakable(Breaks.scala:38) [ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:382) [KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1.apply(KafkaSimpleConsumer.scala:378) [KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) [ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32) [ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at kafka.message.MessageSet.foreach(MessageSet.scala:67) [ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:378) [KamanjaInternalDeps_2.11-1.4.2.jar:0.1-SNAPSHOT]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Range.closed(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lcom/google/common/collect/Range;
	at org.jpmml.evaluator.DiscretizationUtil.toRange(DiscretizationUtil.java:167) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.FieldValueUtil.parseValidRanges(FieldValueUtil.java:596) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.FieldValueUtil.access$000(FieldValueUtil.java:51) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.FieldValueUtil$3.load(FieldValueUtil.java:649) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at org.jpmml.evaluator.FieldValueUtil$3.load(FieldValueUtil.java:645) ~[ExtDependencyLibs_2.11-1.4.2.jar:1.0]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3584) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2372) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2335) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2250) ~[ExtDependencyLibs2_2.11-1.4.2.jar:1.0]
	... 44 more
```

**Comment by ligadata-pokuri** [comment]
Now we migrated from Guava 14.0.1 to 16.0.1. HBase & PMML are working fine with Guava 16.0.1

**Comment by ligadata-pokuri** [comment]
@ligadata-william , can you verify it?

**Comment by ligadata-william** [comment]
@ligadata-pokuri I still see this in the latest 1.5.0.Test

**Comment by ligadata-pokuri** [comment]
Not able to repro it with the version I build. William can you verify it and let me know what is the issue you have.

**Comment by ligadata-william** [comment]
I'm not sure why yet but this issue only persists when built on mac. If I build this on linux and run it on linux or mac, this issue no longer persists. Perhaps something to do with sbt on os x. Some more investigation is needed. Until then:

WORKAROUND: Build from source on linux when running pmml models

Removing verify but dropping this down to a P2 for now.

**Comment by ligadata-pokuri** [comment]
@ligadata-william , assigning this to only you. You can investigate when you have time.
